"""initial check

Revision ID: 1648259439ab
Revises: 
Create Date: 2023-07-28 21:15:38.916503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1648259439ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('guild_id', sa.String(length=500), nullable=True),
    sa.Column('credo', sa.String(length=500), nullable=True),
    sa.Column('galactic_power', sa.String(length=500), nullable=True),
    sa.Column('required_level', sa.Integer(), nullable=True),
    sa.Column('total_members', sa.Integer(), nullable=True),
    sa.Column('guild_reset_time', sa.DateTime(), nullable=True),
    sa.Column('last_db_update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('ally_code', sa.Integer(), nullable=True),
    sa.Column('tg_id', sa.String(length=100), nullable=True),
    sa.Column('tg_nic', sa.String(length=100), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('reid_points', sa.String(length=100), nullable=True),
    sa.Column('lastActivityTime', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.String(length=100), nullable=True),
    sa.Column('arena_rank', sa.Integer(), nullable=True),
    sa.Column('fleet_arena_rank', sa.Integer(), nullable=True),
    sa.Column('galactic_power', sa.Integer(), nullable=True),
    sa.Column('character_galactic_power', sa.Integer(), nullable=True),
    sa.Column('ship_galactic_power', sa.Integer(), nullable=True),
    sa.Column('guild_join_time', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=5000), nullable=True),
    sa.Column('last_swgoh_updated', sa.DateTime(), nullable=True),
    sa.Column('guild_currency_earned', sa.String(length=100), nullable=True),
    sa.Column('arena_leader_base_id', sa.String(length=50), nullable=True),
    sa.Column('ship_battles_won', sa.Integer(), nullable=True),
    sa.Column('pvp_battles_won', sa.Integer(), nullable=True),
    sa.Column('pve_battles_won', sa.Integer(), nullable=True),
    sa.Column('pve_hard_won', sa.Integer(), nullable=True),
    sa.Column('galactic_war_won', sa.Integer(), nullable=True),
    sa.Column('guild_raid_won', sa.Integer(), nullable=True),
    sa.Column('guild_exchange_donations', sa.Integer(), nullable=True),
    sa.Column('season_status', sa.Integer(), nullable=True),
    sa.Column('season_full_clears', sa.Integer(), nullable=True),
    sa.Column('season_successful_defends', sa.Integer(), nullable=True),
    sa.Column('season_league_score', sa.Integer(), nullable=True),
    sa.Column('season_undersized_squad_wins', sa.Integer(), nullable=True),
    sa.Column('season_promotions_earned', sa.Integer(), nullable=True),
    sa.Column('season_banners_earned', sa.Integer(), nullable=True),
    sa.Column('season_offensive_battles_won', sa.Integer(), nullable=True),
    sa.Column('season_territories_defeated', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('guild')
    # ### end Alembic commands ###
