"""Namespace(name='test', func=<function generate at 0x00000198BE1EFF40>)

Revision ID: 88f1cc1c2320
Revises: 
Create Date: 2023-07-20 20:02:29.854439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f1cc1c2320'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
