"""Namespace(name='test', func=<function generate at 0x0000024BA2EAFF40>)

Revision ID: 91c3aa04019e
Revises: 
Create Date: 2023-07-20 20:53:04.586058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c3aa04019e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('fleet_arena_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'fleet_arena_rank')
    # ### end Alembic commands ###
